FROM node:14-alpine as buildstage
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci
RUN npm install -g react-scripts@4.0.1
COPY . ./

# REACT BUILD VARIABLES
ARG REACT_APP_AUTHOR_HANDLE
ARG REACT_APP_AUTHOR_NAME
ARG REACT_APP_AUTHOR_SOCIAL_PROFILE_LINKEDIN
ARG REACT_APP_AUTHOR_SOCIAL_PROFILE_STEAM
ARG REACT_APP_AUTHOR_SOCIAL_PROFILE_TWITTER
ARG REACT_APP_AUTHOR_WEBSITE
ARG REACT_APP_BITCOIN_ADDRESS
ARG REACT_APP_DEBUG
ARG REACT_APP_DISABLE_INDEXING_P
ARG REACT_APP_DOMAIN_URL
ARG REACT_APP_ISSUE_TRACKER
ARG REACT_APP_ISSUE_TRACKER_DB
ARG REACT_APP_LAST_DB_UPDATE
ARG REACT_APP_NAME
ARG REACT_APP_OPEN_ID_URL
ARG REACT_APP_PAYPAL_ADDRESS
ARG REACT_APP_PRETTY_DOMAIN_URL
ARG REACT_APP_SUPPORT_EMAIL
ENV REACT_APP_AUTHOR_HANDLE=$REACT_APP_AUTHOR_HANDLE
ENV REACT_APP_AUTHOR_NAME=$REACT_APP_AUTHOR_NAME
ENV REACT_APP_AUTHOR_SOCIAL_PROFILE_LINKEDIN=$REACT_APP_AUTHOR_SOCIAL_PROFILE_LINKEDIN
ENV REACT_APP_AUTHOR_SOCIAL_PROFILE_STEAM=$REACT_APP_AUTHOR_SOCIAL_PROFILE_STEAM
ENV REACT_APP_AUTHOR_SOCIAL_PROFILE_TWITTER=$REACT_APP_AUTHOR_SOCIAL_PROFILE_TWITTER
ENV REACT_APP_AUTHOR_WEBSITE=$REACT_APP_AUTHOR_WEBSITE
ENV REACT_APP_BITCOIN_ADDRESS=$REACT_APP_BITCOIN_ADDRESS
ENV REACT_APP_DEBUG=$REACT_APP_DEBUG
ENV REACT_APP_DISABLE_INDEXING_P=$REACT_APP_DISABLE_INDEXING_P
ENV REACT_APP_DOMAIN_URL=$REACT_APP_DOMAIN_URL
ENV REACT_APP_ISSUE_TRACKER_DB=$REACT_APP_ISSUE_TRACKER_DB
ENV REACT_APP_ISSUE_TRACKER=$REACT_APP_ISSUE_TRACKER
ENV REACT_APP_LAST_DB_UPDATE=$REACT_APP_LAST_DB_UPDATE
ENV REACT_APP_NAME=$REACT_APP_NAME
ENV REACT_APP_OPEN_ID_URL=$REACT_APP_OPEN_ID_URL
ENV REACT_APP_PAYPAL_ADDRESS=$REACT_APP_PAYPAL_ADDRESS
ENV REACT_APP_PRETTY_DOMAIN_URL=$REACT_APP_PRETTY_DOMAIN_URL
ENV REACT_APP_SUPPORT_EMAIL=$REACT_APP_SUPPORT_EMAIL

RUN npm run build

FROM nginx:stable-alpine
COPY --from=buildstage /app/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d
CMD ["nginx", "-g", "daemon off;"]
