export const appFields = {
  ACHIEVEMENTS_ENABLED: 'achievements_enabled',
  APP_TYPE: 'app_type',
  APPID: 'appid',
  CONTROLLER_SUPPORT: 'controller_support',
  DEVELOPERS: 'developers',
  GENRES: 'genres',
  HDR: 'hdr',
  METASCORE_LINK: 'metascore_link',
  METASCORE: 'metascore',
  MULTIPLAYER: 'multiplayer',
  NAME: 'name',
  OS_LINUX: 'os_linux',
  OS_MAC: 'os_mac',
  OS_WINDOWS: 'os_windows',
  PLAYTIME_FOREVER: 'playtime_forever',
  PRICEHOURSRATIO: 'priceHoursRatio',
  PUBLISHERS: 'publishers',
  RELEASE_DATE: 'release_date',
  SIZE_MB: 'size_mb',
  STATS_ENABLED: 'stats_enabled',
  STEAMCLOUD_ENABLED: 'steamcloud_enabled',
  STORE_PRICE_DEFAULT_USD: 'store_price_default_usd',
  TIMETOBEAT: 'timeToBeat',
  TRADINGCARDS_ENABLED: 'tradingcards_enabled',
  WORKSHOP_ENABLED: 'workshop_enabled',
}
